JKFiles.WebApp/Controllers/MastersDetailsController.cs
using JKFiles.WebApp.Entity;
using JKFiles.WebApp.Models;
using JKFilesBAL;
using JKFIlesEntity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using JKFiles.WebApp.Entity;
using JKFilesDAL;
using PagedList;
using PagedList.Mvc;

namespace JKFiles.WebApp.Controllers
{
    public class MastersDetailsController : Controller
    {
        DAL dbObj = new DAL();
        #region  Masters-by Dhanashree
        BAL objBAL = new BAL();
        CustomerMasterModel custModelObj = new CustomerMasterModel();
        // GET: MastersDetails
        //public ActionResult CustomerMaster()
        //{
        //    custModelObj.custList = objBAL.getCustomerList();
        //    custModelObj.custNoActiveList = objBAL.getCustomerListinactive();
        //    custModelObj.custNoApproveList = objBAL.getCustListNoApprove();
        //    return PartialView("_CustomerMaster", custModelObj);
        //}

        //public ActionResult BrandMaster()
        //{
        //    custModelObj.brandList = objBAL.getBrandList();
        //    custModelObj.brandNoApproveList = objBAL.brandNoApproveList();
        //    custModelObj.brandListNoActiveList = objBAL.brandListNoActiveList();
        //    return PartialView("_BrandMaster", custModelObj);
        //}



        //FileSubType Master 23.05.18
        public ActionResult FileSubType()
        {
            //ProductionMasterModel objProdModel = new ProductionMasterModel();
            //objProdModel.filesizelist = getFileSize();
            //objProdModel.filetTypelist = getFileType();

            FileSpec objfilespec = new FileSpec();
            objfilespec.FileType = "Flat Files";
            DataTable dt = objBAL.getFileSubTypeMaster(objfilespec);
            return View(dt);
        }

        //Cut Specification Master

        #endregion
        #region New Custonmer brand by swapnil
        //public ActionResult CutSpecmaster()
        //{
        //    CutSpecsEntity objcutspecs = new CutSpecsEntity();
        //    //ProductionMasterModel objProdModel = new ProductionMasterModel();
        //    //objProdModel.filesizelist = getFileSize();
        //    //objProdModel.filetTypelist = getFileType();
        //    objcutspecs.cutSpecsNoActiveList = objBAL.getCutSpecNoActiveMaster();
        //    objcutspecs.cutSpecsNoApproveList = objBAL.getCutSpecNoApproveMaster();
        //    objcutspecs.cutSpecsEntityList = objBAL.getCutSpecMaster();
        //    return View(objcutspecs);
        //}
        public ActionResult Details(int Id, string type)
        {
            Utils objUtils = new Utils();
            string connectionstring;
            connectionstring = objUtils.getConnString();
            CustomerMasterModelForActive custModelObj = new CustomerMasterModelForActive();
            // custModelObj = CustomerMasterModelForActive.Find(Id);
            // custModelObj.custModel = objBAL.getCustomerListbyid(Id);
            DataTable dt = new DataTable();
            SqlConnection con = new SqlConnection(connectionstring);
            con.Open();
            SqlCommand cmd = new SqlCommand("sp_get_customer_master_details_byid", con);
            cmd.CommandType = CommandType.StoredProcedure;
            try
            {
                SqlParameter param = new SqlParameter("@id", Id);
                SqlParameter param1 = new SqlParameter("@type", type);
                cmd.Parameters.Add(param1);
                cmd.Parameters.Add(param);
                SqlDataAdapter da = new SqlDataAdapter(cmd);
                con.Close();
                da.Fill(dt);
                custModelObj._id = Convert.ToInt16(dt.Rows[0]["_id"].ToString());
                custModelObj.Cm_Cust_Id = dt.Rows[0]["cm_cust_id"].ToString();
                custModelObj.Cm_Cust_Name = dt.Rows[0]["cm_cust_name"].ToString();
                custModelObj.Cm_Cust_Remarks = dt.Rows[0]["cm_cust_remarks"].ToString();
                custModelObj.cm_request_id = Convert.ToInt16(dt.Rows[0]["cm_request_id"].ToString());
                custModelObj.cm_request_type = dt.Rows[0]["cm_request_type"].ToString();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                cmd.Dispose();
                con.Close();
                con.Dispose();
            }

            return PartialView("_Details", custModelObj);
        }
        public ActionResult REQDetails(int Id, string type)
        {
            Utils objUtils = new Utils();
            string connectionstring;
            connectionstring = objUtils.getConnString();
            CustomerMasterModelForActive custModelObj = new CustomerMasterModelForActive();
            // custModelObj = CustomerMasterModelForActive.Find(Id);
            // custModelObj.custModel = objBAL.getCustomerListbyid(Id);
            DataTable dt = new DataTable();
            SqlConnection con = new SqlConnection(connectionstring);
            con.Open();
            SqlCommand cmd = new SqlCommand("sp_get_customer_master_details_byREQid", con);
            cmd.CommandType = CommandType.StoredProcedure;
            try
            {
                SqlParameter param = new SqlParameter("@id", Id);
                SqlParameter param1 = new SqlParameter("@type", type);
                cmd.Parameters.Add(param1);
                cmd.Parameters.Add(param);
                SqlDataAdapter da = new SqlDataAdapter(cmd);
                con.Close();
                da.Fill(dt);
                custModelObj._id = Convert.ToInt16(dt.Rows[0]["_id"].ToString());
                custModelObj.Cm_Cust_Id = dt.Rows[0]["cm_cust_id"].ToString();
                custModelObj.Cm_Cust_Name = dt.Rows[0]["cm_cust_name"].ToString();
                custModelObj.Cm_Cust_Remarks = dt.Rows[0]["cm_cust_remarks"].ToString();
                custModelObj.cm_request_id = Convert.ToInt16(dt.Rows[0]["cm_request_id"].ToString());
                custModelObj.cm_request_type = dt.Rows[0]["cm_request_type"].ToString();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                cmd.Dispose();
                con.Close();
                con.Dispose();
            }

            return PartialView("_ReqCustDetails", custModelObj);
        }
        public ActionResult REQfilesubtypeDetails(int Id, string type)
        {
            Utils objUtils = new Utils();

            string connectionstring;
            connectionstring = objUtils.getConnString();
            FileSubTypeEntity FileSubTypeModelObj = new FileSubTypeEntity();
            // custModelObj = CustomerMasterModelForActive.Find(Id);
            // custModelObj.custModel = objBAL.getCustomerListbyid(Id);

            DataTable dt = new DataTable();
            SqlConnection con = new SqlConnection(connectionstring);
            con.Open();
            SqlCommand cmd = new SqlCommand("sp_get_fileSubType_details_byREQid", con);
            cmd.CommandType = CommandType.StoredProcedure;
            try
            {
                SqlParameter param = new SqlParameter("@id", Id);
                SqlParameter param1 = new SqlParameter("@type", type);
                cmd.Parameters.Add(param1);
                cmd.Parameters.Add(param);
                SqlDataAdapter da = new SqlDataAdapter(cmd);
                con.Close();
                da.Fill(dt);
                FileSubTypeModelObj.rmcode = dt.Rows[0]["pm_dim_parm_scrnvalue"].ToString();
                FileSubTypeModelObj.wtinkgthousand = dt.Rows[1]["pm_dim_parm_scrnvalue"].ToString();
                FileSubTypeModelObj.description = dt.Rows[2]["pm_dim_parm_scrnvalue"].ToString();
                FileSubTypeModelObj.width = Convert.ToDecimal(dt.Rows[3]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.thikness = Convert.ToDecimal(dt.Rows[4]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.gmssku = dt.Rows[5]["pm_dim_parm_scrnvalue"].ToString();
                FileSubTypeModelObj.mood_length = Convert.ToDecimal(dt.Rows[6]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.lengthmm = Convert.ToDecimal(dt.Rows[7]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.lengthP1mm = Convert.ToDecimal(dt.Rows[8]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.widthatShoulder = Convert.ToDecimal(dt.Rows[9]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.thiknessatshoulder = Convert.ToDecimal(dt.Rows[10]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.widthattip = Convert.ToDecimal(dt.Rows[11]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.thiknessattip = Convert.ToDecimal(dt.Rows[12]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.pointsizeatexactlength = Convert.ToDecimal(dt.Rows[13]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.bodydimentionwidth = Convert.ToDecimal(dt.Rows[14]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.bodydimentionthikness = Convert.ToDecimal(dt.Rows[15]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.bodypointsize = Convert.ToDecimal(dt.Rows[16]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.tapperlengthmm = Convert.ToDecimal(dt.Rows[17]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.lengthaftercuttingbefore = Convert.ToDecimal(dt.Rows[18]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.atshoulder = Convert.ToDecimal(dt.Rows[19]["pm_dim_parm_dwgvalue"].ToString());
                FileSubTypeModelObj.onedge = Convert.ToDecimal(dt.Rows[20]["pm_dim_parm_dwgvalue"].ToString());

JKFiles.WebApp/Views/MastersDetails/Customer_Brand_Master.cshtml
@{
    ViewBag.Title = "Customer_Brand_Master";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}

<div class="content">
    <div class="col-md-6"><h4>Customer Brand Country Details</h4></div>

    <div class="col-md-12">


        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a href="#customer" data-toggle="tab" aria-expanded="true">Customer</a></li>
                <li class=""><a href="#brand" data-toggle="tab" aria-expanded="false">Brand</a></li>
                <li class=""><a href="#custbrand" data-toggle="tab" aria-expanded="true">Customer And Brand</a></li>
            </ul>
            <div class="tab-content">

                <!-- /.tab-pane -->
                <div class="tab-pane active" id="customer">
                    <div style="clear:both"></div><br>
                    @Html.Action("Customer")
                </div>
                <!-- /.tab-pane -->
                <!-- /.tab-pane -->
                <div class="tab-pane  " id="brand">
                    @Html.Action("BrandMasterView")

                </div>

                <div class="tab-pane " id="custbrand">
                    @Html.Action("CustomerBrand")
                </div>


                <div style="clear:both"></div>



            </div><!-- /.tab-content -->
        </div>


    </div>



    <br>
    <br>
    <br>


    <div style="clear:both"></div>

</div>
<!-- BY SWAPNIL-->
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<div id='myModal' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>

</div>
<div class="modal fade in" id="appc" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabelc"></h5>
                <button type="button" class="close jk-mt-20" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <label>Enter Remark</label>
                <textarea name="or_remarks" id="or_remarks" cols="" rows=""></textarea>
                <h4> Confirm Approval?</h4>
                <a href="" class="btn btn-primary" onclick="UpdatecApprove()">Approve</a>
                <a href="#" class="btn btn-primary" onclick="RejectcRequest()">Reject</a>
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>

        </div>
    </div>
</div>
<div id='myModal1' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent1'></div>
        </div>
    </div>

</div>
<script src="~/SharedCss/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<script>
    var requestid = "";
    var requestNo = "";
    var requesttype = "";
    function RejectApprovec(i, j, k) {
        $("#exampleModalLabelc").empty();
        requestid = i;
        requestNo = j;
        requesttype = k;
        $("#exampleModalLabelc").append("Request No :", requestid);
    }
    function RejectcRequest() {
                $.ajax({
                    url: '@Url.Action("RejectApprove", "MastersDetails")',
                    data: { ID: requestNo, type: requesttype },
                    type: 'GET',
                    dataType: "json",
                    success: function (data) {
                        location = data.url;
                    },
                    error: function () {
                        alert("No Records reject");
                    }
                });
            }
    function UpdatecApprove() {
    $.ajax({
        url: '@Url.Action("UpdateApprove", "MastersDetails")',
        data: { ID: requestNo, type: requesttype },
        type: 'POST',
        dataType: "json",

        success: function (data) {
             location = data.url;

        },
        error: function () {
            alert("No Records approve");
        }
    });
    }
</script>
<script>
                var TeamDetailPostBackURL1 = '@Url.Action("Brand", "MastersDetails")';
                $(function () {
                    $(".anchorDetail").click(function () {
                        debugger;
                        var $buttonClicked = $(this);
                        var id1 = $buttonClicked.attr('data-id');
                        var emailrogh = id1.split(",");
                        var id = emailrogh[0];// show priya@gmail.com
                        var type = emailrogh[1]
                        var options = { "backdrop": "static", keyboard: true };
                        $.ajax({
                            type: "GET",
                            url: TeamDetailPostBackURL1,
                            contentType: "application/json; charset=utf-8",
                            data: { "Id": id ,"type":type},
                            datatype: "json",
                            success: function (data) {
                                debugger;
                                $('#myModalContent').html(data);
                                $('#editcustomer').modal(options);
                                $('#myModal').modal('show');

                            },
                            error: function () {
                                alert("Dynamic content load failed.");
                            }
                        });
                    });
                    //$("#closebtn").on('click',function(){
                    //    $('#myModal').modal('hide');

                    $("#closbtn").click(function () {
                        $('#myModal').modal('hide');
                    });

                    $('.CountClick').click(function () {
                        debugger;
                        var productID = getParameterByName('ID', $(this).attr("href"));
                        var countID = "Count" + productID;
                        var totalID = "Total" + productID;

                        var countElement = document.getElementById(countID);
                        var totalElement = document.getElementById(totalID);
                        var rowElement = document.getElementById(productID);

                        $.ajax({
                            cache: false,
                            url: $(this).attr("href"), // used data from url
                            datatype: "text",
                            type: "POST",
                            success: function (response) {

                                var count = parseInt(response.Count);

                                if (count > 0) {
                                    countElement.innerText = response.Count;
                                    totalElement.innerText = response.Total;
                                }
                                else {
                                    rowElement.innerHTML = "";
                                }
                            },
                            error: function () {
                                $("#divResult").html("ERROR");
                            }
                        });

                        return false;
                    });
                });



</script>
<script>
                var TeamDetailPostBackURL = '@Url.Action("Details", "MastersDetails")';
    $(function () {
        $(".anchorDetail1").click(function () {
            debugger;
            var $buttonClicked = $(this);
            var id1 = $buttonClicked.attr('data-id');
            var emailrogh = id1.split(",");
            var id = emailrogh[0];// show priya@gmail.com
            var type = emailrogh[1]
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: TeamDetailPostBackURL,
                contentType: "application/json; charset=utf-8",
                data: { "Id": id, "type": type },
                datatype: "json",
                success: function (data) {
                    debugger;
                    $('#myModalContent').html(data);
                    $('#editcustomer').modal(options);
                    $('#myModal').modal('show');

                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
        //$("#closebtn").on('click',function(){
        //    $('#myModal').modal('hide');

        $("#closbtn").click(function () {
            $('#myModal').modal('hide');
        });

        $('.CountClick').click(function () {
            debugger;
            var productID = getParameterByName('ID', $(this).attr("href"));
            var countID = "Count" + productID;
            var totalID = "Total" + productID;

            var countElement = document.getElementById(countID);
            var totalElement = document.getElementById(totalID);
            var rowElement = document.getElementById(productID);

            $.ajax({
                cache: false,
                url: $(this).attr("href"), // used data from url
                datatype: "text",
                type: "POST",
                success: function (response) {

                    var count = parseInt(response.Count);

                    if (count > 0) {
                        countElement.innerText = response.Count;
                        totalElement.innerText = response.Total;
                    }
                    else {
                        rowElement.innerHTML = "";
                    }
                },
                error: function () {
                    $("#divResult").html("ERROR");
                }
            });

            return false;
        });
    });



</script>
<script>
    //$('#myTab a').click(function (e) {
    //    e.preventDefault();
    //    $(this).tab('show');
    //});

    //// store the currently selected tab in the hash value
    //$("ul.nav-tabs > li > a").on("shown.bs.tab", function (e) {
    //    var id = $(e.target).attr("href").substr(1);
    //    window.location.hash = id;
    //});

    //// on load of the page: switch to the currently selected tab
    //var hash = window.location.hash;
    //$('#myTab a[href="' + hash + '"]').tab('show');

    //$(function () {
    //    $('a[data-toggle="tab"]').on('shown', function (e) {
    //        //save the latest tab using a cookie:
    //        $.cookie('last_tab', $(e.target).attr('href'));
    //    });

    //    //activate latest tab, if it exists:
    //    var lastTab = $.cookie('last_tab');
    //    if (lastTab) {
    //        $('ul.nav-tabs').children().removeClass('active');
    //        $('a[href=' + lastTab + ']').parents('li:first').addClass('active');
    //        $('div.tab-content').children().removeClass('active');
    //        $(lastTab).addClass('active');
    //    }
    //});

</script>

JKFiles.WebApp/Views/MastersDetails/REQfileSizeDetails.cshtml
@model JKFIlesEntity.FileSizeDetailsEntity


<div class="modal-header">
    <h5 class="modal-title" id="new">Add New File Size</h5>
    <button type="button" class="close jk-mt-20" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form action="@Url.Action("EditfileSizeDetails", "ProductionDetails")" method="post">
    <div class="modal-body">
        @Html.HiddenFor(model => model._id, new { @class = "form-control " })
        @Html.HiddenFor(model => model.fs_request_id, new { @class = "form-control " })
        @Html.HiddenFor(model => model.fs_request_type, new { @class = "form-control " })
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th width="100" style="width: 10px">Parameter Name</th>
                    <th width="144">Parameter Value</th>

                </tr>
                <tr>
                    <td>File Size</td>
                    <td>@Html.TextBoxFor(model => model.fs_size_inches, new { @class = "form-control ", @placeholder = "File Size ", @required = "Required" })</td>


                </tr>
                <tr>
                    <td>File Size Code</td>
                    <td>@Html.TextBoxFor(model => model.fs_size_code, new { @class = "form-control ", @placeholder = "File Size Code" })</td>

                </tr>
                <tr>
                    <td colspan="3">@Html.TextAreaFor(model => model.fs_size_remarks, new { @class = "form-control ", @cols = 80, @rows = 3, @placeholder = "Remark(optional)", @required = "Required" })</td>
                </tr>
            </tbody>
        </table>



    </div>
    <div class="modal-footer">
        <div>
            <a href="#" type="button" class="btn btn-default" data-dismiss="modal">Cancel</a>
            @*<a href="#reject" class="btn btn-primary" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample">Reject</a>
                <a href="submit" type="button" class="btn btn-primary" data-dismiss="modal">Use Existing</a>*@
            <button type="submit" class="btn btn-primary">OK</button>
        </div>
    </div>
</form>

JKFiles.WebApp/Views/MastersDetails/_BrandDetails.cshtml
@model JKFIlesEntity.BrandDetailsEntity


    <div class="modal-header">
        <h5 class="modal-title" id="new">Add New Brand</h5>
        <button type="button" class="close jk-mt-20" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <form action="@Url.Action("SaveBrandDetails","MastersDetails")" method="post">
        <div class="modal-body">
           
                @Html.HiddenFor(model => model._id, new { @class = "form-control " })
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th width="100" style="width: 10px">Parameter Name</th>
                        <th width="144">Parameter Value</th>

                    </tr>
                    <tr>
                        <td>Brand Id</td>
                        <td>@Html.TextBoxFor(model => model.bm_brand_id, new { @class = "form-control ", @placeholder = "Brand Id", @required = "Required" })</td>


                    </tr>
                    <tr>
                        <td>Brand Name</td>
                        <td>@Html.TextBoxFor(model => model.bm_brand_name, new { @class = "form-control ", @placeholder = "Brand Name", @required = "Required" })</td>

                    </tr>
                    <tr>
                        <td colspan="3">@Html.TextAreaFor(model => model.bm_brand_remarks, new { @class = "form-control ", @cols = 80, @rows = 3, @placeholder = "Remark(optional)", @required = "Required" })</td>
                    </tr>
                </tbody>
            </table>
            
          
            
        </div>
        <div class="modal-footer">
            <div>
                <a href="#" type="button" class="btn btn-default" data-dismiss="modal">Cancel</a>
                @*<a href="#reject" class="btn btn-primary" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample">Reject</a>
                <a href="submit" type="button" class="btn btn-primary" data-dismiss="modal">Use Existing</a>*@
                <button type="submit" class="btn btn-primary">Send for Approval</button>
            </div>
            </div>
    </form>

JKFiles.WebApp/Views/MastersDetails/_CustomerBrand.cshtml
@*@model JKFiles.WebApp.Models.CustomerMasterModel*@
@using PagedList.Mvc
@model  PagedList.IPagedList<JKFIlesEntity.CustomerDetailsEntity>
@{
//ViewBag.Title = "_CustomerBrand";
// Layout = "~/Views/Shared/MasterPage.cshtml";
}
<div class="col-md-12">

    <a href="CustomerBrand">
        <input type="button" class="btn btn-default pull-right" style="margin-right:5px" value="Show All" />
    </a>
</div>
<div id="divPartialView1">
   
    <div class="tab-pane active" id="custbrand">

        @Html.Action("Customerbrandddl")


        <div style="clear:both"></div>
        <div class="table-responsive">

            <table width="100%" border="1" bordercolor="#CCC">
                <tr>
                    <td width="15%" bgcolor="#e8e8e8" class="text-black">
                        <div align="center">
                            Ship to
                            Country
                        </div>
                        <div align="center"></div>
                    </td>
                    <td width="16%" height="31" bgcolor="#e8e8e8" class="text-black"><div align="center">Customer Code</div></td>
                    <td width="29%" bgcolor="#e8e8e8" class="text-black"><div align="center">Customer Name</div></td>
                    <td width="11%" bgcolor="#e8e8e8" class="text-black"><div align="center">Brand Code</div></td>
                    <td width="29%" bgcolor="#e8e8e8" class="text-black"><div align="center">Brand Name</div></td>

                </tr>

                @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td><div align="center">@Model[i].pr_ship2country_name</div></td>
                    <td><div align="center">@Model[i].pr_cust_id</div></td>
                    <td><div align="center">@Model[i].pr_cust_name</div></td>
                    <td height="20" width="78"><div align="center">@Model[i].pr_brand_id</div></td>
                    <td width="114"><div align="center">@Model[i].pr_brand_desc</div></td>
                </tr>
                }



                @*@foreach (var list in Model.custList)
                    {
                        <tr>
                            <td><div align="center">@list.pr_ship2country_name</div></td>
                            <td><div align="center">@list.pr_cust_id</div></td>
                            <td><div align="center">@list.pr_cust_name</div></td>
                            <td height="20" width="78"><div align="center">@list.pr_brand_id</div></td>
                            <td width="114"><div align="center">@list.pr_brand_desc</div></td>

                        </tr>
                    }*@
            </table>
            <div id="container">
                <p></p>
                <p></p>
                <div class="pagination">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                    of @Model.PageCount   @Html.PagedListPager(Model, page => Url.Action("Customer_Brand_Master", new { page, cstname = ViewBag.cstname, brand = ViewBag.brand, countryname = ViewBag.countryname }))
                </div>
            </div>


            <p class="style1">&nbsp;</p>
        </div>

    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<script src="~/SharedCss/plugins/jQuery/jQuery-2.1.4.min.js"></script>


<script>
    $(document).ready(function () {
        
            var codedata = '@(TempData["msg"])';
            if (codedata != '') {
                alert('@(TempData["msg"])');
            }
     
        $(".ChangeApprove").change(function () {
            $("#loading").css("display", "block");
            var cstname = $("#Cm_Cust_Name").val();
            var brand = $("#brandName").val();
            var countryname = $("#countryName").val();
            // var filetype = $("#filetype").val();
            //var cutstand = $("#cut_standard").val();
            $.ajax({
                url: '@Url.Action("CustomerBrand", "MastersDetails")',
                data: { cstname: cstname, brand: brand, countryname: countryname },
                type: 'GET',
                dataType: "html",
                success: function (data) {
                    $("#divPartialView1").html(data);
                    $("#loading").css("display", "none");
                },
                error: function () {
                    alert("No Records Found");
                }
            });

        });


    });
</script>