JKFiles.WebApp/Controllers/UnitController.cs
using JKFiles.WebApp.ActionFilters;
using JKFiles.WebApp.Models;
using JKFilesBAL;
using JKFIlesEntity;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace JKFiles.WebApp.Controllers
{
    [HandleError]
    [SessionTimeout]
    public class UnitController : Controller
    {
        BAL objBAL = new BAL();
        // GET: Unit
        public ActionResult Index(string UnitID)
        {
            
            return View();
        }

        public ActionResult ManagePlantUnit()
        {
            UnitMasterModel umobj = new UnitMasterModel();
            umobj.unitlist = get_unitlist();
            umobj.plantdropdownlist = objBAL.getPlantDropdownList();
            umobj.unitdropdownlist = objBAL.getunitDropdownList();
            return PartialView("_ManagePlantUnit", umobj);
        }

        public ActionResult ManagePlantSearch(string UnitID)
        {

            UnitMasterModel umobj = new UnitMasterModel();
            umobj.unitlist = get_unitlist();
            if (!String.IsNullOrEmpty(UnitID))
            {
                umobj.unitlist = umobj.unitlist.Where(x => x.uni_unit_code == UnitID).ToList();
            }
            umobj.plantdropdownlist = objBAL.getPlantDropdownList();
            umobj.unitdropdownlist = objBAL.getunitDropdownList();
            return PartialView("_ManagePlantUnit", umobj);
        }

        public ActionResult IndexUnitTest()
        {
            UnitMasterModel umobj = new UnitMasterModel();
            umobj.unitlist = get_unitlist();
            return Json(new { success = true, unitlist = umobj.unitlist }, JsonRequestBehavior.AllowGet);
        }

        //public ActionResult ExportToExcel()
        //{
        //    var gv = new GridView();
        //    gv.DataSource = get_unitlist();
        //    gv.DataBind();

        //    Response.ClearContent();
        //    Response.Buffer = true;
        //    Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xlsx");
        //    Response.ContentType = "application/ms-excel";

        //    Response.Charset = "";
        //    StringWriter objStringWriter = new StringWriter();
        //    HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);

        //    gv.RenderControl(objHtmlTextWriter);

        //    Response.Output.Write(objStringWriter.ToString());
        //    Response.Flush();
        //    Response.End();

        //    return View("Index");

        //}
        public ActionResult test()
        {
            return View();
        }
        public List<UnitMasterModel> get_unitlist()
        {
            string flag = "unitlist";
            DataTable dt = objBAL.getUnitlist(flag);
            UnitMasterModel modelobj = new UnitMasterModel();
            List<UnitMasterModel> list = new List<UnitMasterModel>();
            if (dt.Rows.Count > 0 && dt != null)
            {
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    UnitMasterModel objPlant = new UnitMasterModel();
                    objPlant.uni_unit_code = dt.Rows[i]["uni_unit_code"].ToString();
                    objPlant.uni_unit_name = dt.Rows[i]["uni_unit_name"].ToString();
                    objPlant.uni_unit_type = dt.Rows[i]["uni_unit_type"].ToString();
                    objPlant.uni_unit_attachTo = dt.Rows[i]["uni_unit_attachTo"].ToString();
                    objPlant.uni_unit_absentisum = Convert.ToInt32(dt.Rows[i]["uni_unit_absentisum"].ToString());
                    objPlant.uni_unit_material_downtime = Convert.ToInt32(dt.Rows[i]["uni_unit_material_downtime"].ToString());
                    list.Add(objPlant);
                }
            }
            return list.ToList();
        }

        public ActionResult ManageUnitNorm(string UnitID,string UnitType, string valueStream)
        {
            UnitMasterModel umobj = new UnitMasterModel();
            umobj.unitNormlist = get_unitnormlist();
            if (!String.IsNullOrEmpty(UnitID))
            {
                umobj.unitNormlist = umobj.unitNormlist.Where(x => x.val_unit_code == UnitID).ToList();
            }
            if (!String.IsNullOrEmpty(UnitType))
            {
                umobj.unitNormlist = umobj.unitNormlist.Where(x => x.uni_unit_type == UnitType).ToList();
            }
            if (!String.IsNullOrEmpty(valueStream))
            {
                umobj.unitNormlist = umobj.unitNormlist.Where(x => x.val_valuestream_code == valueStream).ToList();
            }
           
            return Json(new { success = true, Unitlist = umobj.unitNormlist }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ManageUnitNormview()
        {
            UnitMasterModel umobj = new UnitMasterModel();
            //umobj.unitNormlist = get_unitnormlist();
            umobj.unitdropdownlist = objBAL.getunitDropdownList();
            umobj.unitvaluestreamlist = objBAL.getunitvalueStreamDropdownList();
            return PartialView("_ManageUnitNormview", umobj);
        }

        public List<UnitMasterModel> get_unitnormlist()
        {
            string flag = "unitnormlist";
            DataTable dt = objBAL.getUnitnormlist(flag);
            UnitMasterModel modelobj = new UnitMasterModel();
            List<UnitMasterModel> list = new List<UnitMasterModel>();
            if (dt.Rows.Count > 0 && dt != null)
            {
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    UnitMasterModel objPlant = new UnitMasterModel();
                    objPlant.val_unit_code = dt.Rows[i]["val_unit_code"].ToString();
                    objPlant.uni_unit_name = dt.Rows[i]["uni_unit_name"].ToString();
                    objPlant.uni_unit_type = dt.Rows[i]["uni_unit_type"].ToString();
                    objPlant.uni_unit_attachTo = dt.Rows[i]["uni_unit_attachTo"].ToString();
                    objPlant.val_valuestream_code = dt.Rows[i]["val_valuestream_code"].ToString();
                    objPlant.val_alternate_valuestream_code = dt.Rows[i]["val_alternate_valuestream_code"].ToString();
                    objPlant.ft_ftype_desc = dt.Rows[i]["ft_ftype_desc"].ToString();
                    list.Add(objPlant);
                }
            }
            return list.ToList();
        }

        public ActionResult ManageValueStream(string valueStream)
        {
            ValueStreamMasterModel umobj = new ValueStreamMasterModel();
            //List<ValueStreamMasterModel> mvslist = new List<ValueStreamMasterModel>();
            umobj.unitvaluestreamlist = get_unitvaluestremlist();

            if (!String.IsNullOrEmpty(valueStream))
            {
                umobj.unitvaluestreamlist = umobj.unitvaluestreamlist.Where(x => x.ft_ftype_code == valueStream).ToList();
            }
            umobj.valueStreamDropdownList = objBAL.getvalueStreamDropdownList();
            return PartialView("_ManagevalueStreamview", umobj);
        }

        public ActionResult ManagevalueStreamview()
        {
            ValueStreamMasterModel umobj = new ValueStreamMasterModel();
            umobj.unitvaluestreamlist = get_unitvaluestremlist();
            umobj.valueStreamDropdownList = objBAL.getvalueStreamDropdownList();
            return PartialView("_ManagevalueStreamview", umobj);
        }

        public List<ValueStreamMasterModel> get_unitvaluestremlist()
        {
            string flag = "unitvaluestreamlist";
            DataTable dt = objBAL.get_unitvaluestremlist(flag);
            ValueStreamMasterModel modelobj = new ValueStreamMasterModel();
            List<ValueStreamMasterModel> list = new List<ValueStreamMasterModel>();
            if (dt.Rows.Count > 0 && dt != null)
            {
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    ValueStreamMasterModel objPlant = new ValueStreamMasterModel();
                    objPlant.ft_ftype_code = dt.Rows[i]["ft_ftype_code"].ToString();
                    objPlant.ft_ftype_desc = dt.Rows[i]["ft_ftype_desc"].ToString();
                    list.Add(objPlant);
                }
            }
            return list.ToList();
        }

        [HttpPost]
        public ActionResult AddUnit(UnitMasterModel model)
        {
            if (ModelState.IsValid)
            {
                UnitMasterEntity Ancobj = new UnitMasterEntity();
                Ancobj.uni_unit_code = model.uni_unit_attachTo + model.uni_unit_code;
                Ancobj.uni_unit_name = model.uni_unit_name;
                Ancobj.uni_unit_type = "A";
                Ancobj.uni_unit_attachTo = model.uni_unit_attachTo;
                Ancobj.uni_unit_absentisum = model.uni_unit_absentisum;
                Ancobj.uni_unit_material_downtime = model.uni_unit_material_downtime;
                Ancobj.uni_createby = Session["User_Id"].ToString();
                Ancobj.uni_approveby = Session["User_Id"].ToString();
                Ancobj.flag = "InsertUnit";
                objBAL.SaveUnit(Ancobj);
                ViewBag.alert = "Record insert successfully";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult PlantCode(string PlantID )
        {
            if (!String.IsNullOrEmpty(PlantID))
            {
                string PlantCode = objBAL.PlantforPlantCode(PlantID);

                return Json(new { success = true, PlantCode = PlantCode }, JsonRequestBehavior.AllowGet);
            }
           
        return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public ActionResult AddValueStream(ValueStreamMasterModel model)
        {
            if (ModelState.IsValid)
            {

JKFiles.WebApp/Views/Unit/Index.cshtml
@model JKFiles.WebApp.Models.UnitMasterModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
<div class="content">

    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Unit Details</h3>
        </div>
        <div class="box-body">

            <div class="nav-tabs-custom">
                
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#vstream" data-toggle="tab" aria-expanded="false">Unit List</a></li>
                        <li class=""><a href="#valuestream" data-toggle="tab" aria-expanded="true">Value Stream (VS) List</a></li>
                        <li class=""><a href="#unorms" data-toggle="tab" aria-expanded="true">VS By Unit</a></li>

                    </ul>
             
                <div class="tab-content">
                    <!-- /.tab-pane -->
                    <div class="tab-pane active " id="vstream">
                        @Html.Action("ManagePlantUnit")
                    </div>
                    <div class="tab-pane " id="unorms">
                        @Html.Action("ManageUnitNormview")
                    </div>
                    <div class="tab-pane  " id="valuestream">
                        @Html.Action("ManagevalueStreamview")
                    </div>
                    <div style="clear:both"></div>
                </div>

        </div>
        <!-- /.box-body -->
    </div>


</div>

</div>
<div style="clear:both"></div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

JKFiles.WebApp/Views/Unit/_ManagePlantUnit.cshtml
@model JKFiles.WebApp.Models.UnitMasterModel

@{
    ViewBag.Title = "_ManagePlantUnit";
}


<!-- /.tab-pane -->
<div class="tab-pane active" id="vstream">
    <div class="form-group col-md-2">
        @Html.DropDownListFor(model => model.uni_unit_code, new SelectList(Model.unitdropdownlist, "uni_unit_code", "uni_unit_name"), "Select Unit", new { @class = "form-control select3", @id = "UnitID" })
        @Html.ValidationMessageFor(m => m.uni_unit_code)
    </div>
    <a href="#" class=" btn btn-primary pull-right" data-toggle="modal" data-target="#newuvs">Add New </a>
    <a href="Index">
        <input type="button" class="btn btn-default pull-right" style="margin-right:5px" value="Show All" />
    </a>
    <div style="clear:both"></div>

    @*<span class="box-title">Unit = Plant/Anscillary</span>*@
    <div style="clear:both"></div>
    <br><div id="divPartialView1">
        <div class="table-responsive">
            <table width="100%" border="1" bordercolor="#CCCCCC" id="Unittbl">
                <tr>
                    <td width="11%" height="32" bgcolor="#e8e8e8" class=" text-black"><div align="center">Unit Name</div></td>
                    <td width="7%" bgcolor="#e8e8e8" class=" text-black"><div align="center">Unit Type</div></td>
                    <td width="8%" bgcolor="#e8e8e8" class=" text-black"><div align="center">Unit Code</div></td>
                    <td width="7%" bgcolor="#e8e8e8" class=" text-black"><div align="center">Attached to</div></td>
                    <td width="7%" bgcolor="#e8e8e8" class=" text-black"><div align="center">Absentism (%)</div></td>
                    <td width="7%" bgcolor="#e8e8e8" class=" text-black"><div align="center">Material Downtime (%)</div></td>
                </tr>
                <tbody></tbody>
                @foreach (var item in Model.unitlist)
                        {
                    <tr>
                        <td><div align="center">@item.uni_unit_name</div></td>
                        <td><div align="center">@item.uni_unit_type</div></td>
                        <td>
                            <div align="center">@item.uni_unit_code</div>
                        </td>
                        <td><div align="center">@item.uni_unit_attachTo</div></td>
                        <td><div align="center">@item.uni_unit_absentisum</div></td>
                        <td><div align="center">@item.uni_unit_material_downtime</div></td>
                    </tr>
                                                        }

            </table>
        </div>
    </div>
</div>
<div style="clear:both"></div>

<div class="modal fade" id="newuvs" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="new">Add Ancillary</h5>
                <button type="button" class="close jk-mt-20" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="unitform" action="@Url.Action("AddUnit", "Unit")"  method="post">
                    <div class="form-group col-md-6">

                            @Html.DropDownListFor(model => model.pla_plant_code, new SelectList(Model.plantdropdownlist, "pla_plant_code", "pla_plant_name"), "Main Plant", new { @class = "form-control selectplantcode", @id = "PlantID" })
                            @Html.ValidationMessageFor(m => m.pla_plant_code)
                      
                    </div>

                    <div class="form-group col-md-6">
                        <input type="text" class="form-control" id="uni_unit_name" name="uni_unit_name" placeholder="Ancillary Name" required="required">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="text" class="form-control" id="uni_unit_code" name="uni_unit_code" placeholder="Unit Code" required="required" maxlength="4"  onkeyup="CheckUnitCode()">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="text" class="form-control" id="uni_unit_attachTo" name="uni_unit_attachTo" placeholder="Attached to" readonly>
                    </div>


                    <div class="form-group col-md-6">
                        <input type="text" class="form-control" id="uni_unit_absentisum" name="uni_unit_absentisum" onkeypress="return isNumberKey(event)" placeholder="Absentism(%)" required="required">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="text" class="form-control" id="uni_unit_material_downtime" name="uni_unit_material_downtime" onkeypress="return isNumberKey(event)" placeholder="Material Downtime(%)" required="required">
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Ok</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>


<div class="modal fade" id="edituvs" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="new">Edit Unit Value Stream </h5>
                <button type="button" class="close jk-mt-20" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-md-6">
                    <label for="" class="">Unit Name</label>
                    <div class="form-group"><input type="text" class="form-control " name="textfield3" id="textfield13" value="Vapi" readonly /> </div>

                </div>

                <div class="col-md-6">
                    <label for="" class="">Unit Type</label>
                    <div class="form-group"><input type="text" class="form-control " name="textfield3" id="textfield13" value="Plant" readonly /> </div>
                </div>

                <div class="col-md-6">
                    <label for="" class="">Unit Code</label>
                    <div class="form-group"><input type="text" class="form-control " name="textfield3" id="textfield13" value="VAPM" readonly /> </div>
                </div><div class="col-md-6">
                    <label for="" class="">Attached to</label>
                    <div class="form-group"><input type="text" class="form-control " name="textfield3" id="textfield13" value="VAPM" readonly /> </div>

                </div>

                <div class="col-md-6">
                    <label for="" class="">Absentism(%)</label>

                    <div class="form-group"><input type="text" class="form-control " name="textfield3" id="textfield13" value="1" /> </div>
                </div>
                <div class="col-md-6">
                    <label for="" class="">Material Downtime(%)</label>

                    <div class="form-group"><input type="text" class="form-control " name="textfield3" id="textfield13" value="2" /> </div>
                </div>

            </div>
            <div style="clear:both"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onClick="myFunction()">Ok</button>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<script src="~/SharedCss/plugins/jQuery/jQuery-2.1.4.min.js"></script>


<script>
    $(document).ready(function () {
        if ('@ViewBag.alert' != "") {
            alert('@ViewBag.alert');
        }

        $(".select3").change(function () {
            $("#loading").css("display", "block");
            var UnitID = $("#UnitID").val();

            $.ajax({
                url: '@Url.Action("ManagePlantSearch", "Unit")',
                data: { UnitID: UnitID },
                type: 'GET',
                dataType: "html",
                success: function (data) {
                    $("#vstream").empty();
                    $("#vstream").html(data);
                    $("#loading").css("display", "none");
                },
                error: function () {
                    alert("No Records Found");
                }
            });
        });

        $(".selectplantcode").change(function () {
            var PlantID = $("#PlantID").val();

            $.ajax({
                url: '@Url.Action("PlantCode", "Unit")',
                data: { PlantID: PlantID },
                type: 'POST',
                dataType: "json",
                success: function (data) {
                    $("#uni_unit_attachTo").val(data.PlantCode);
                },
                error: function () {
                    alert("No Records Found");
                }
            });
        });
    });


    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }

    function CheckUnitCode() {
        var uni_unit_code = $("#uni_unit_code").val();
        var uni_unit_attachTo = $("#uni_unit_attachTo").val();
        $.ajax({
            url: '@Url.Action("CheckUnitCode", "Unit")',
            data: { uni_unit_code: uni_unit_code, uni_unit_attachTo: uni_unit_attachTo },
            type: 'GET',
            dataType: "json",
            success: function (data) {
                if (data.success) {
                    alert("Unit Code already exists");
                    $("#uni_unit_code").val('');
                } else {
                }
            },
            error: function () {
            }
        });
    }
</script>

JKFiles.WebApp/Views/Unit/_ManagevalueStreamview.cshtml
@model JKFiles.WebApp.Models.ValueStreamMasterModel

@{
    ViewBag.Title = "_ManagevalueStreamview";
}
<div class="tab-pane active" id="valuestream">
    <div class="form-group col-md-2">
        @Html.DropDownListFor(model => model.ft_ftype_code, new SelectList(Model.valueStreamDropdownList, "ft_ftype_code", "ft_ftype_desc"), "Select Value Stream", new { @class = "form-control select3", @id = "valueStreamID" })
        @Html.ValidationMessageFor(m => m.ft_ftype_code)
    </div>
    <a href="Index">
        <input type="button" class="btn btn-default pull-right" style="margin-right:5px" value="Show All" />
    </a>
    <div style="clear:both"></div>

    <div class="col-md-6" id="divPartialView1">
        <div class="table-responsive">
            <table width="100%" border="1" bordercolor="#CCCCCC" id="valuestreamunit">
                <tr>
                    <td width="20%" height="32" bgcolor="#e8e8e8" class=" text-black"><div align="center">  Value    Stream Name</div></td>
                    <td width="14%" bgcolor="#e8e8e8" class=" text-black"><div align="center"> Family Code</div></td>
                    @foreach (var item in Model.unitvaluestreamlist)
                        {
                    <tr>
                        <td><div align="center">@item.ft_ftype_code</div></td>
                        <td><div align="center">@item.ft_ftype_desc</div></td>
                    </tr>
                        }
                </table>
            </div>
        </div>
    </div>

   
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/SharedCss/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".select3").change(function () {
                $("#loading").css("display", "block");
                var valueStream = $("#valueStreamID").val();
                $.ajax({
                    url: '@Url.Action("ManageValueStream", "Unit")',
                    data: { valueStream: valueStream },
                    type: 'GET',
                    dataType: "html",
                    success: function (data) {
                        $("#valuestream").empty();
                        $("#valuestream").html(data);
                        $("#loading").css("display", "none");
                    },
                    error: function () {
                        alert("No Records Found");
                    }
                });
            });
        });

        function CheckValusreamCode() {
            var val_valuestream_code = $("#ft_ftype_code").val();
            $.ajax({
                url: '@Url.Action("CheckValusreamCode", "Unit")',
                data: { val_valuestream_code: val_valuestream_code },
                type: 'GET',
                dataType: "json",
                success: function (data) {
                    if (data.success) {
                        alert("Value Stream Code already exists");

                    } else {

                    }
                },
                error: function () {
                }
            });
        }
    </script>